---
  - name: crear grupo operador
    group:
      name: operador
      state: present

  - name: crear usuario opers
    user:
      name: "{{ item }}"
      shell: /bin/bash
      groups: operador
      append: yes
    with_items: "{{ usuarios }}"

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ item }}"
      state: present
      key: "{{ lookup('file', '/home/pue/.ssh/id_ed25519.pub') }}"
    with_items: "{{ usuarios }}"

